### ISSUE TITLE
add  eurostreaming.diy and Anime World

### ISSUE THREAD

**Issue by Heisenberge89** [UrloMythus/MammaMia#1]
Good morning great job , could you add some sites where to see sub ita TV series like “ eurostreaming.diy”? As with streaming community you only see those translated into Italian. Also if possible add “ Anime World ” to be able to see anime dubbed in Italian and not only subtitled . Thank you very much

**Comment by UrloMythus** [comment]
Hi, I will see. I am quite sure multiple audios should appear with SC but I will check. Anyways since there are a tons of subtitles plugin on Stremio you can just use them to get the dubbed videos. 
Moreover I had already planned to add an extra anime provider.

**Comment by UrloMythus** [comment]
Added Animeworld. Eurostreaming added a captcha and it is not really reversable rn.
