### ISSUE TITLE
Errors with adding to Stremio

### ISSUE THREAD

**Issue by zlee1** [UrloMythus/MammaMia#11]
After following the self-hosting instructions and successfully starting the server, I'm unable to install the add-on to Stremio. 

This is the result when I use the install button:
![image](https://github.com/user-attachments/assets/a56b58a0-71ef-4ff2-bbd7-1beb91ddb619)

This is the result when I copy and paste the generated link:
![image](https://github.com/user-attachments/assets/e6b32267-e14a-44c2-8111-7cb23a644836)

And here is the output from the server in both instances:
![image](https://github.com/user-attachments/assets/09ccda2a-fa91-4642-9a9a-44e08b676531)

I probably missed something stupid, but any help here would be appreciated. Thank you!

**Comment by UrloMythus** [comment]
> After following the self-hosting instructions and successfully starting the server, I'm unable to install the add-on to Stremio.
> 
> This is the result when I use the install button: ![image](https://private-user-images.githubusercontent.com/70806768/395732275-a56b58a0-71ef-4ff2-bbd7-1beb91ddb619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjg5MzcsIm5iZiI6MTczNDI2ODYzNywicGF0aCI6Ii83MDgwNjc2OC8zOTU3MzIyNzUtYTU2YjU4YTAtNzFlZi00ZmYyLWJiZDctMWJlYjkxZGRiNjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDEzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0Y2YyZTUwMDEwYmJmMzI2OTExMjE2M2UyMzNhZTI3NzI3Mzc1MTM0MGE1NzkzYWM5ZTVlM2Q4ZTU3Y2NhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MD4fxKP_AAtSKSgphDHZDeQ7JLRFST9PuInMI8Z6Duc)
> 
> This is the result when I copy and paste the generated link: ![image](https://private-user-images.githubusercontent.com/70806768/395732309-e6b32267-e14a-44c2-8111-7cb23a644836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjg5MzcsIm5iZiI6MTczNDI2ODYzNywicGF0aCI6Ii83MDgwNjc2OC8zOTU3MzIzMDktZTZiMzIyNjctZTE0YS00NGMyLTgxMTEtN2NiMjNhNjQ0ODM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDEzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMGZjMzRjMDc2ZmE2MGU2MjJmNmZmYzM4YWRiMDYwODA5ZGU4M2YzZDViMGZjZDJiNzRmZWFhZWQxNjViODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iC2P_gyfRaUwquHocNEQR0JZeI3MP5GWM2i96oWbIz4)
> 
> And here is the output from the server in both instances: ![image](https://private-user-images.githubusercontent.com/70806768/395732341-09ccda2a-fa91-4642-9a9a-44e08b676531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjg5MzcsIm5iZiI6MTczNDI2ODYzNywicGF0aCI6Ii83MDgwNjc2OC8zOTU3MzIzNDEtMDljY2RhMmEtZmE5MS00NjQyLTlhOWEtNDRlMDhiNjc2NTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDEzMTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZGI1NDdkMDJlZWQ1YTkxNDA2MTk3NjJlNWIyYjRkN2VlZWJiNGJkNDZkOGZlNDVjODMxMGViZWU5YzVkY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QXkFMxyLuZ5_GO68uYaMSamwGT7B26T0ruQNk8MYjjw)
> 
> I probably missed something stupid, but any help here would be appreciated. Thank you!

Hello, are you trying to do it from the same device where the server is running? If not then the server needs to be on HTTPS and that is why it is failing to fetch it.

**Comment by zlee1** [comment]
Hi! The server is running on the same device I'm trying to access it from.

**Comment by UrloMythus** [comment]
> Hi! The server is running on the same device I'm trying to access it from.
You need to install the add-on from this url : http://127.0.0.1:8080/   
If you do not want to expose the add-on on 0.0.0.0 at all then you can change that value in the config and put this instead: 127.0.0.1    
Note that if you will ever need to add HTTPS to expose it on other devices then you need 0.0.0.0 as host.

**Comment by zlee1** [comment]
Thank you, that resolved my problem.
