### ISSUE TITLE
New websites and metadata issue

### ISSUE THREAD

**Issue by autumnalpilot** [UrloMythus/MammaMia#2]
Hi, and thank you for this amazing work. Could I ask you to add these other streaming websites please?
- altadefinizione.democrat
- filmsenzalimiti.food

Since they added some eurostreaming.delivery captchas, what do you think about using selenium for scraping? Because that site is really the primary resource in Italy for TV series. The other sites don't have series unless they're just released. I don't know how to program well yet, otherwise I would have gladly contributed. Thank you very much.

ps. I have a question: does MammaMia use imdb to search for metadata? I ask because it happened that after searching on trakt or tmdb from the stremio search bar, MammaMia opened another film. Actually, it happens for many films, unfortunately. Take for example the animated Beauty and the beast of 1991. Via streamingcommunity it finds me another film, while from lordchannel it takes the right cartoon. What's the matter?

**Comment by UrloMythus** [comment]
Both sites are just clones of GuardaHD which is added by Stremify. For eurostreaming I won't use Selenium:
1 It is heavy, and not ideal on  a server that needs to serve contents to a lot of people
2 It won't help, even if you render javascript you have to complete a captcha
Yes I use tmdb/imdb for fetching metadata. Usually that thing with StreamingCOmmunity only happens when StreamingCommunity doesn't have that movie but it has one with similar name and the same release year

**Comment by autumnalpilot** [comment]
Hi,
1. I invite you to try opening Beauty and the Beast, the 1991 animated film. It opens up something completely different and the other existing Beauty and the Beast films are all of different dates. And trust me, it's not the only case, I wouldn't have reported it to you otherwise. There are also cases of movies or TV series, already present on StreamingCommunity, that have a name but open up a completely different movie, and there are quite a few cases unfortunately. It's just that it gets confused. Once you've searched for a movie, you should try to make it do the search differently by working with the movie id itself, maybe.
2. Could you also add TV2000 to Italian TV?
3. When could you implement the possibility of hiding the TVChannels section from the stremio home?
4. In fact Eurostreaming is also on Stremify, unfortunately it never works nor finds out anything, even with the latest fix: [https://github.com/stremify/stremify/tree/main/server /routes](https://github.com/stremify/stremify/tree/main/server/routes)
With seleniumbase, a lighter version, I can accept captchas from heavy sites like unknowncheats after logging in with chrome windowless mode.

Thank you anyway, appreciate your availability.

**Comment by UrloMythus** [comment]
1 I will look into it if it's actually on Streaming Community website. I can not work directly with movie IDs cause the site doesn't support them.
2 I don't know, maybe if I find a source easy enough to add 
3 this is in WIP
4 the eurostreaming on stremify is just a clone of guardaserie, not the real one. 
And still seleniumbase is not really suitable

**Comment by UrloMythus** [comment]
Tried Beauty and the Beast, and it correctly opens the one that is on Streaming Community Website. Be sure to disable Fast Search, that is almost certainly why it doesn't get the right one.
