### ISSUE TITLE
Anime non trovato

### ISSUE THREAD

**Issue by GabriFrz** [UrloMythus/MammaMia#3]
Ciao, stavo provando a guardare Kizumonogataris su stremio, ho installato sia mammamia con animeworld che kitsu anime. Ma non risulta nessuno stream disponibile. Qualcuno sa quale potrebbe essere il problema?

**Comment by UrloMythus** [comment]
Ci guarderò, spesso é perché i nomi degli anime sono leggermente differenti su animeworld

**Comment by GabriFrz** [comment]
Ah okay, grazie mille

**Comment by UrloMythus** [comment]
Ciao, ho appena guardato sul sito di animeworld ed effettivamente non è disponibile. Di conseguenza non è disponibile nel mio add-on

**Comment by GabriFrz** [comment]
Ciao, ho dato un'occhiata anche io al sito peró kizumonogatari mi esce tra i risultati ed è anche possibile vederlo, forse è stato aggiunto di recente?

**Comment by UrloMythus** [comment]
Ci riguarderò allora

**Comment by UrloMythus** [comment]
Fixato : )
