### ISSUE TITLE
aggiungere https e docker-compose

### ISSUE THREAD

**Issue by blademckain** [UrloMythus/MammaMia#4]
Salve,
vi chiedo se sia possibile, aggiungere il supporto per https e un docker-compose.
Per chi ha varie smart tv in casa, sarebbe utile, hostare in locale su un proprio server interno l'addon e far puntare a questo le varie smarttv

grazie

**Comment by UrloMythus** [comment]
Ciao, il supporto per HTTPS non è un qualcosa che fornisce l'add-on di per se. Ci sono vari metodi per aggiungere l'https quali ngix, duck-dns, cloudfare tunnel etc.
Per quanto riguarda un docker compose vedrò, per ora c'è un DockerFile che dovrebbe andare bene lo stesso.

**Comment by UrloMythus** [comment]
Vedi https://github.com/UrloMythus/MammaMia/issues/6#issue-2649191623 Per Docker Compose
