### ISSUE TITLE
Streamingcommunity non disponibile

### ISSUE THREAD

**Issue by emaschi5** [UrloMythus/MammaMia#5]
Ciao e grazie per questo addon fantastico, da oggi sembra non essere disponibile streamingcommunity, era fantastico aveva tutto, il sito non è cambiato, sempre .computer, speriamo sia un problema risolvibile @UrloMythus

**Comment by d-beezee** [comment]
@UrloMythus non conosco molto bene come funzionano gli addon (né mammamia né gli addon di stremio in generale) ma facendo un po' di debugging e reverse engineering in giro ho visto che 

/%7CSC%7C/stream/series/tmdb:tt0303461:1:2.json mi ritorna 404

Se cambio l'impersonate da chrome120 a chrome110 in `Src/API/streamingcommunity.py` mi ritorna i dati corretti.

**Comment by UrloMythus** [comment]
Yep, risolto :)
